Algoritmo "exemplo01"
var n: vetor[1..3,1..3] de inteiro
   i, j: inteiro

Inicio
   para i de 1 ate 3 faca
      para j de 1 ate 3 faca
         escreva ("Digite um valor para a posição [",i, ",", j, "]: ")
         leia(n[i,j])
      fimpara
   fimpara

   para i de 1 ate 3 faca
      para j de 1 ate 3 faca

         escreva(n[i,j])
      fimpara
      escreval
   fimpara
Fimalgoritmo